
/*
 * This file was generated by the SOM Compiler.
 * FileName: Source\Wps2Pc2.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.2
 *     SOM Emitter emith: 2.41
 */

/*
 * 
 *                             WPS2PC2.idl
 *              Copyright (C) by Stangl Roman, 1995, 1999
 * This Code may be freely distributed, provided the Copyright isn't
 * removed, under the conditions indicated in the documentation.
 * 
 * WPS2PC2.C    PC/2's interface to the WPS. This WPS DLL allows you
 *              to drag WPS objects onto, which are then converted
 *              into a format understandable by PC/2. This newly
 *              structure can then be dropped onto PC/2's Setup dialog
 *              to add Menuentries corresponding to the dropped WPS
 *              objects to PC/2's Popup Menu. E.g. this allows you to
 *              create a Menuentry that is equivalent to a WPS DOS
 *              program object, inclusive any DOS settings.
 * 
 * SOMObject
 *    WPObject
 *       WPAbstract
 * 
 */


#ifndef SOM_Wps2Pc2_h
#define SOM_Wps2Pc2_h


/*
 * Passthru lines: File: "C.h", "before"
 */

VOID        FillList2Listbox(WPSOBJECTLIST *pListRoot, ULONG ulRecursionLevel);                
/*--------------------------------------------------------------------------------------*\     
 * METHOD: wpOpen                                                           (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      Called when the WPS2PC2 WPS icon gets opened via the context menu.              *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
WPSOBJECTLIST                                                                                  
            *ConvertObject2MenuData(void *pObject,                                       
                                    ULONG ulRecursionLevel);                                   
/*--------------------------------------------------------------------------------------*\     
 * METHOD: ConvertObject2MenuData                                           (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      Called when a WPS instances have been dropped over WPS2PC2 to query the         *      
 *      instances data, allocate MENUDATA structures in unnamed shared memory and       *      
 *      convert WPS object data into a WPSOBJECTLIST LIST understandable by PC/2.       *      
 *      The pointer pObject is a WPObject *, but under SOM 2 it is not defined when     *      
 *      processing the header file, to keep a common code between SOM 1 and SOM 2 we    *      
 *      have to add a cast.                                                             *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
PBYTE       AllocateSharedMem(void);                                                           
/*--------------------------------------------------------------------------------------*\     
 * METHOD: AllocateSharedMem                                                (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function allocates a memory block of an unnamed shared memory, whose       *      
 *      starting address is passed to PC2.EXE via Drag'n Drop which also frees this     *      
 *      memory (otherwise WPS2PC2.DLL provides a menuitem to free it) before a new      *      
 *      shared memory can be allocated. The allocated memory is not commited, so any    *      
 *      access leads to an access violation, which invokes the exception handler to     *      
 *      commit it.                                                                      *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
PBYTE       GetFreeSharedMem(ULONG ulSharedMemSize);                                           
/*--------------------------------------------------------------------------------------*\     
 * METHOD: GetFreeSharedMem                                                 (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function allocated the next free ulSharedMemSize sized block within the    *      
 *      shared memory allocated by AllocateSharedMem().                                 *      
 *      Pointer DLLPc2Wps.pbSharedMemNextFree is updated accordingly.                   *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
void        DeAllocateSharedMem(void);                                                      
/*--------------------------------------------------------------------------------------*\     
 * METHOD: DeAllocateSharedMem                                              (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function deallocates the unnamed shared memory allocated with              *      
 *      AllocateSharedMem().                                                            *      
 *      The control structure entries about shared memory are updated accordingly.      *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
#pragma linkage(_Exception, System)                                                            
ULONG       _Exception(PEXCEPTIONREPORTRECORD pExcRepRecord,                                   
                       PEXCEPTIONREGISTRATIONRECORD pExcRegRecord,                             
                       PCONTEXTRECORD pCtxRecord,                                              
                       PVOID  pVoid);                                                          
/*--------------------------------------------------------------------------------------*\     
 * METHODE: _Exception                                                      (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function is the exception handler for WPS2PC2.DLL. It is only used to      *      
 *      commit unnamed shared memory, which was allocated uncommited and accessed,      *      
 *      leading to an access violation.                                                 *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
ULONG           ProcessDragOver(PDRAGINFO pdrgInfo);                                           
/*--------------------------------------------------------------------------------------*\     
 * METHOD: ProcessDragOver                                                  ( ) Private *      
 *                                                                          (x) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function processes the dragover events to allow or deny dropping WPS       *      
 *      Objects.                                                                        *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
ULONG           ProcessDrop(PDRAGINFO pdrgInfo, PDRAGITEM pdrgItem);                           
/*--------------------------------------------------------------------------------------*\     
 * METHOD: ProcessDrop                                                      ( ) Private *      
 *                                                                          (x) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function processes the drop event, which does analyse the WPS Objects      *      
 *      having been dropped.                                                            *      
\*--------------------------------------------------------------------------------------*/     
                                                                                               
MRESULT EXPENTRY                                                                               
            WPS2PC2_MainWindowProc(HWND hwnd, ULONG msg, MPARAM mp1, MPARAM mp2);              
/*--------------------------------------------------------------------------------------*\     
 * METHOD: WPS2PC2_MainWindowProc                                           (x) Private *      
 *                                                                          ( ) Public  *      
 * DESCRIPTION:                                                                         *      
 *      This function is the main window procedure of the window created when selecting *      
 *      "Open -> WPS 2 PC/2" from the "Open ->" submenu at the context menu.            *  
\*--------------------------------------------------------------------------------------*/     


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef Wps2Pc2
#define Wps2Pc2 SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_Wps2Pc2
    #define M_Wps2Pc2 SOMObject
#endif /* M_Wps2Pc2 */

/*
 * End of user-defined types.
 */

#define Wps2Pc2_MajorVersion 1
#define Wps2Pc2_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define Wps2Pc2NewClass Wps2Pc2c
#pragma linkage(Wps2Pc2c, system)
#define Wps2Pc2ClassData Wps2Pc2d
#define Wps2Pc2CClassData Wps2Pc2x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <Wps2Pc2.h>
/*--------------Migration------------*/
#define Wps2Pc2_classObj Wps2Pc2ClassData.classObject
#define _Wps2Pc2 Wps2Pc2_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK Wps2Pc2NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(Wps2Pc2NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct Wps2Pc2ClassDataStructure {
	SOMAny *classObject;
} SOMDLINK Wps2Pc2ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct Wps2Pc2CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK Wps2Pc2CClassData;

/*
 * New and Renew macros for Wps2Pc2
 */
#define Wps2Pc2New() \
   (_somNew(_Wps2Pc2 ? _Wps2Pc2 : Wps2Pc2NewClass(Wps2Pc2_MajorVersion, Wps2Pc2_MinorVersion)))
#define Wps2Pc2Renew(buf) \
   (_somRenew(_Wps2Pc2 ? _Wps2Pc2 : Wps2Pc2NewClass(Wps2Pc2_MajorVersion, Wps2Pc2_MinorVersion), buf))

/*
 * Override method: wpDragOver
 */
#define Wps2Pc2_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define Wps2Pc2_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpModifyPopupMenu
 */
#define Wps2Pc2_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define Wps2Pc2_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpMenuItemSelected
 */
#define Wps2Pc2_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define Wps2Pc2_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define Wps2Pc2_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define Wps2Pc2_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define Wps2Pc2_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define Wps2Pc2_wpAddSettingsPages WPObject_wpAddSettingsPages
#define Wps2Pc2_wpAddToObjUseList WPObject_wpAddToObjUseList
#define Wps2Pc2_wpAllocMem WPObject_wpAllocMem
#define Wps2Pc2_wpAppendObject WPObject_wpAppendObject
#define Wps2Pc2_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define Wps2Pc2_wpClose WPObject_wpClose
#define Wps2Pc2_wpCnrInsertObject WPObject_wpCnrInsertObject
#define Wps2Pc2_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define Wps2Pc2_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define Wps2Pc2_wpConfirmDelete WPObject_wpConfirmDelete
#define Wps2Pc2_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define Wps2Pc2_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define Wps2Pc2_wpCopyObject WPObject_wpCopyObject
#define Wps2Pc2_wpCreateAnother WPObject_wpCreateAnother
#define Wps2Pc2_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define Wps2Pc2_wpCreateShadowObject WPObject_wpCreateShadowObject
#define Wps2Pc2_wpDelete WPObject_wpDelete
#define Wps2Pc2_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define Wps2Pc2_wpDisplayHelp WPObject_wpDisplayHelp
#define Wps2Pc2_wpDisplayMenu WPObject_wpDisplayMenu
#define Wps2Pc2_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define Wps2Pc2_wpDraggedOverObject WPObject_wpDraggedOverObject
#define Wps2Pc2_wpDroppedOnObject WPObject_wpDroppedOnObject
#define Wps2Pc2_wpEndConversation WPObject_wpEndConversation
#define Wps2Pc2_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define Wps2Pc2_wpFindUseItem WPObject_wpFindUseItem
#define Wps2Pc2_wpFormatDragItem WPObject_wpFormatDragItem
#define Wps2Pc2_wpFree WPObject_wpFree
#define Wps2Pc2_wpFreeMem WPObject_wpFreeMem
#define Wps2Pc2_wpHide WPObject_wpHide
#define Wps2Pc2_wpInitData WPObject_wpInitData
#define Wps2Pc2_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define Wps2Pc2_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define Wps2Pc2_wpMoveObject WPObject_wpMoveObject
#define Wps2Pc2_wpPrintObject WPObject_wpPrintObject
#define Wps2Pc2_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define Wps2Pc2_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define Wps2Pc2_wpQueryConfirmations WPObject_wpQueryConfirmations
#define Wps2Pc2_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define Wps2Pc2_wpQueryDefaultView WPObject_wpQueryDefaultView
#define Wps2Pc2_wpQueryDetailsData WPObject_wpQueryDetailsData
#define Wps2Pc2_wpQueryError WPObject_wpQueryError
#define Wps2Pc2_wpSetFolder WPObject_wpSetFolder
#define Wps2Pc2_wpQueryFolder WPObject_wpQueryFolder
#define Wps2Pc2_wpQueryIcon WPObject_wpQueryIcon
#define Wps2Pc2_wpQueryIconData WPObject_wpQueryIconData
#define Wps2Pc2_wpQueryMinWindow WPObject_wpQueryMinWindow
#define Wps2Pc2_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define Wps2Pc2_wpQueryStyle WPObject_wpQueryStyle
#define Wps2Pc2_wpSetTaskRec WPObject_wpSetTaskRec
#define Wps2Pc2_wpFindTaskRec WPObject_wpFindTaskRec
#define Wps2Pc2_wpQueryTitle WPObject_wpQueryTitle
#define Wps2Pc2_wpRegisterView WPObject_wpRegisterView
#define Wps2Pc2_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define Wps2Pc2_wpRender WPObject_wpRender
#define Wps2Pc2_wpRenderComplete WPObject_wpRenderComplete
#define Wps2Pc2_wpReplaceObject WPObject_wpReplaceObject
#define Wps2Pc2_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define Wps2Pc2_wpRestore WPObject_wpRestore
#define Wps2Pc2_wpRestoreData WPObject_wpRestoreData
#define Wps2Pc2_wpRestoreLong WPObject_wpRestoreLong
#define Wps2Pc2_wpRestoreState WPObject_wpRestoreState
#define Wps2Pc2_wpRestoreString WPObject_wpRestoreString
#define Wps2Pc2_wpSaveData WPObject_wpSaveData
#define Wps2Pc2_wpSaveImmediate WPObject_wpSaveImmediate
#define Wps2Pc2_wpSaveDeferred WPObject_wpSaveDeferred
#define Wps2Pc2_wpSaveLong WPObject_wpSaveLong
#define Wps2Pc2_wpSaveState WPObject_wpSaveState
#define Wps2Pc2_wpSaveString WPObject_wpSaveString
#define Wps2Pc2_wpScanSetupString WPObject_wpScanSetupString
#define Wps2Pc2_wpSetConcurrentView WPObject_wpSetConcurrentView
#define Wps2Pc2_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define Wps2Pc2_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define Wps2Pc2_wpSetDefaultView WPObject_wpSetDefaultView
#define Wps2Pc2_wpSetError WPObject_wpSetError
#define Wps2Pc2_wpSetIconHandle WPObject_wpSetIconHandle
#define Wps2Pc2_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define Wps2Pc2_wpSetupOnce WPObject_wpSetupOnce
#define Wps2Pc2_wpSetIcon WPObject_wpSetIcon
#define Wps2Pc2_wpSetIconData WPObject_wpSetIconData
#define Wps2Pc2_wpSetMinWindow WPObject_wpSetMinWindow
#define Wps2Pc2_wpSetStyle WPObject_wpSetStyle
#define Wps2Pc2_wpModifyStyle WPObject_wpModifyStyle
#define Wps2Pc2_wpSetTitle WPObject_wpSetTitle
#define Wps2Pc2_wpSetup WPObject_wpSetup
#define Wps2Pc2_wpSwitchTo WPObject_wpSwitchTo
#define Wps2Pc2_wpUnInitData WPObject_wpUnInitData
#define Wps2Pc2_wpViewObject WPObject_wpViewObject
#define Wps2Pc2_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define Wps2Pc2_wpQueryHandle WPObject_wpQueryHandle
#define Wps2Pc2_wpUnlockObject WPObject_wpUnlockObject
#define Wps2Pc2_wpObjectReady WPObject_wpObjectReady
#define Wps2Pc2_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define Wps2Pc2_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define Wps2Pc2_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define Wps2Pc2_wpIsDeleteable WPObject_wpIsDeleteable
#define Wps2Pc2_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define Wps2Pc2_wpSetObjectID WPObject_wpSetObjectID
#define Wps2Pc2_wpQueryObjectID WPObject_wpQueryObjectID
#define Wps2Pc2_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define Wps2Pc2_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define Wps2Pc2_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define Wps2Pc2_wpFindViewItem WPObject_wpFindViewItem
#define Wps2Pc2_wpLockObject WPObject_wpLockObject
#define Wps2Pc2_wpIsLocked WPObject_wpIsLocked
#define Wps2Pc2_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define Wps2Pc2_wpWaitForClose WPObject_wpWaitForClose
#define Wps2Pc2_somDefaultInit SOMObject_somDefaultInit
#define Wps2Pc2_somDestruct SOMObject_somDestruct
#define Wps2Pc2_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define Wps2Pc2_somDefaultAssign SOMObject_somDefaultAssign
#define Wps2Pc2_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define Wps2Pc2_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define Wps2Pc2_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define Wps2Pc2_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define Wps2Pc2_somDefaultVAssign SOMObject_somDefaultVAssign
#define Wps2Pc2_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define Wps2Pc2_somInit SOMObject_somInit
#define Wps2Pc2_somFree SOMObject_somFree
#define Wps2Pc2_somUninit SOMObject_somUninit
#define Wps2Pc2_somGetClass SOMObject_somGetClass
#define Wps2Pc2_somGetClassName SOMObject_somGetClassName
#define Wps2Pc2_somGetSize SOMObject_somGetSize
#define Wps2Pc2_somIsA SOMObject_somIsA
#define Wps2Pc2_somIsInstanceOf SOMObject_somIsInstanceOf
#define Wps2Pc2_somRespondsTo SOMObject_somRespondsTo
#define Wps2Pc2_somDispatch SOMObject_somDispatch
#define Wps2Pc2_somClassDispatch SOMObject_somClassDispatch
#define Wps2Pc2_somCastObj SOMObject_somCastObj
#define Wps2Pc2_somResetObj SOMObject_somResetObj
#define Wps2Pc2_somDispatchV SOMObject_somDispatchV
#define Wps2Pc2_somDispatchL SOMObject_somDispatchL
#define Wps2Pc2_somDispatchA SOMObject_somDispatchA
#define Wps2Pc2_somDispatchD SOMObject_somDispatchD
#define Wps2Pc2_somPrintSelf SOMObject_somPrintSelf
#define Wps2Pc2_somDumpSelf SOMObject_somDumpSelf
#define Wps2Pc2_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_Wps2Pc2_h */

#ifndef SOM_M_Wps2Pc2_h
#define SOM_M_Wps2Pc2_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_Wps2Pc2
#define M_Wps2Pc2 SOMObject
#endif
#include <wpabs.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_Wps2Pc2_MajorVersion 1
#define M_Wps2Pc2_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_Wps2Pc2NewClass Wps2Pc2c
#pragma linkage(Wps2Pc2c, system)
#define M_Wps2Pc2ClassData Wps2Pc2d
#define M_Wps2Pc2CClassData Wps2Pc2x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_Wps2Pc2_classObj M_Wps2Pc2ClassData.classObject
#define _M_Wps2Pc2 M_Wps2Pc2_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_Wps2Pc2NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_Wps2Pc2NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_Wps2Pc2ClassDataStructure {
	SOMAny *classObject;
} SOMDLINK M_Wps2Pc2ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_Wps2Pc2CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_Wps2Pc2CClassData;

/*
 * New and Renew macros for M_Wps2Pc2
 */
#define M_Wps2Pc2New() \
   (_somNew(_M_Wps2Pc2 ? _M_Wps2Pc2 : M_Wps2Pc2NewClass(M_Wps2Pc2_MajorVersion, M_Wps2Pc2_MinorVersion)))
#define M_Wps2Pc2Renew(buf) \
   (_somRenew(_M_Wps2Pc2 ? _M_Wps2Pc2 : M_Wps2Pc2NewClass(M_Wps2Pc2_MajorVersion, M_Wps2Pc2_MinorVersion), buf))

/*
 * Override method: wpclsQueryIconData
 */
#define M_Wps2Pc2_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsInitData
 */
#define M_Wps2Pc2_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_Wps2Pc2_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_Wps2Pc2_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_Wps2Pc2_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryStyle
 */
#define M_Wps2Pc2_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_Wps2Pc2_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_Wps2Pc2_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_Wps2Pc2_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_Wps2Pc2_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_Wps2Pc2_wpclsNew M_WPObject_wpclsNew
#define M_Wps2Pc2_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_Wps2Pc2_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_Wps2Pc2_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_Wps2Pc2_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_Wps2Pc2_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_Wps2Pc2_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_Wps2Pc2_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_Wps2Pc2_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_Wps2Pc2_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_Wps2Pc2_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_Wps2Pc2_wpclsSetError M_WPObject_wpclsSetError
#define M_Wps2Pc2_wpclsQueryError M_WPObject_wpclsQueryError
#define M_Wps2Pc2_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_Wps2Pc2_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_Wps2Pc2_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_Wps2Pc2_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_Wps2Pc2_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_Wps2Pc2_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_Wps2Pc2_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_Wps2Pc2_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_Wps2Pc2_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_Wps2Pc2_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_Wps2Pc2_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_Wps2Pc2_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_Wps2Pc2__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_Wps2Pc2__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_Wps2Pc2__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_Wps2Pc2__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_Wps2Pc2_somNew SOMClass_somNew
#define M_Wps2Pc2_somNewNoInit SOMClass_somNewNoInit
#define M_Wps2Pc2_somRenew SOMClass_somRenew
#define M_Wps2Pc2_somRenewNoInit SOMClass_somRenewNoInit
#define M_Wps2Pc2_somRenewNoZero SOMClass_somRenewNoZero
#define M_Wps2Pc2_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_Wps2Pc2_somAllocate SOMClass_somAllocate
#define M_Wps2Pc2_somDeallocate SOMClass_somDeallocate
#define M_Wps2Pc2__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_Wps2Pc2__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_Wps2Pc2_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_Wps2Pc2_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_Wps2Pc2_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_Wps2Pc2_somInitClass SOMClass_somInitClass
#define M_Wps2Pc2_somInitMIClass SOMClass_somInitMIClass
#define M_Wps2Pc2_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_Wps2Pc2_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_Wps2Pc2_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_Wps2Pc2_somClassReady SOMClass_somClassReady
#define M_Wps2Pc2_somGetApplyStub SOMClass_somGetApplyStub
#define M_Wps2Pc2_somGetClassData SOMClass_somGetClassData
#define M_Wps2Pc2_somSetClassData SOMClass_somSetClassData
#define M_Wps2Pc2_somGetClassMtab SOMClass_somGetClassMtab
#define M_Wps2Pc2_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_Wps2Pc2_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_Wps2Pc2_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_Wps2Pc2_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_Wps2Pc2_somGetMemberToken SOMClass_somGetMemberToken
#define M_Wps2Pc2_somGetMethodData SOMClass_somGetMethodData
#define M_Wps2Pc2_somGetRdStub SOMClass_somGetRdStub
#define M_Wps2Pc2_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_Wps2Pc2_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_Wps2Pc2_somGetMethodToken SOMClass_somGetMethodToken
#define M_Wps2Pc2_somGetName SOMClass_somGetName
#define M_Wps2Pc2_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_Wps2Pc2_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_Wps2Pc2_somGetNumMethods SOMClass_somGetNumMethods
#define M_Wps2Pc2_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_Wps2Pc2_somGetParent SOMClass_somGetParent
#define M_Wps2Pc2_somGetParents SOMClass_somGetParents
#define M_Wps2Pc2_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_Wps2Pc2_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_Wps2Pc2_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_Wps2Pc2_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_Wps2Pc2_somFindMethod SOMClass_somFindMethod
#define M_Wps2Pc2_somFindMethodOk SOMClass_somFindMethodOk
#define M_Wps2Pc2_somFindSMethod SOMClass_somFindSMethod
#define M_Wps2Pc2_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_Wps2Pc2_somLookupMethod SOMClass_somLookupMethod
#define M_Wps2Pc2_somCheckVersion SOMClass_somCheckVersion
#define M_Wps2Pc2_somDescendedFrom SOMClass_somDescendedFrom
#define M_Wps2Pc2_somSupportsMethod SOMClass_somSupportsMethod
#define M_Wps2Pc2_somDefinedMethod SOMClass_somDefinedMethod
#define M_Wps2Pc2_somOverrideMtab SOMClass_somOverrideMtab
#define M_Wps2Pc2_somDefaultInit SOMObject_somDefaultInit
#define M_Wps2Pc2_somDestruct SOMObject_somDestruct
#define M_Wps2Pc2_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_Wps2Pc2_somDefaultAssign SOMObject_somDefaultAssign
#define M_Wps2Pc2_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_Wps2Pc2_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_Wps2Pc2_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_Wps2Pc2_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_Wps2Pc2_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_Wps2Pc2_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_Wps2Pc2_somInit SOMObject_somInit
#define M_Wps2Pc2_somFree SOMObject_somFree
#define M_Wps2Pc2_somUninit SOMObject_somUninit
#define M_Wps2Pc2_somGetClass SOMObject_somGetClass
#define M_Wps2Pc2_somGetClassName SOMObject_somGetClassName
#define M_Wps2Pc2_somGetSize SOMObject_somGetSize
#define M_Wps2Pc2_somIsA SOMObject_somIsA
#define M_Wps2Pc2_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_Wps2Pc2_somRespondsTo SOMObject_somRespondsTo
#define M_Wps2Pc2_somDispatch SOMObject_somDispatch
#define M_Wps2Pc2_somClassDispatch SOMObject_somClassDispatch
#define M_Wps2Pc2_somCastObj SOMObject_somCastObj
#define M_Wps2Pc2_somResetObj SOMObject_somResetObj
#define M_Wps2Pc2_somDispatchV SOMObject_somDispatchV
#define M_Wps2Pc2_somDispatchL SOMObject_somDispatchL
#define M_Wps2Pc2_somDispatchA SOMObject_somDispatchA
#define M_Wps2Pc2_somDispatchD SOMObject_somDispatchD
#define M_Wps2Pc2_somPrintSelf SOMObject_somPrintSelf
#define M_Wps2Pc2_somDumpSelf SOMObject_somDumpSelf
#define M_Wps2Pc2_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_Wps2Pc2_h */
